name: agendamento
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.10.1

  cloud_firestore: ^5.6.2

  flutter_plugin_android_lifecycle: ^2.0.24

  firebase_auth: ^5.5.0

  image_picker: ^1.1.2

  timezone: ^0.9.0

  flutter_localizations:
    sdk: flutter
    

  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/hospital.png
    - assets/gato.png

    - assets/gato2.png